### PR TITLE
Attempt at a R workflow for geolocation

### PR DESCRIPTION
**Pull request by tpoisot**
This is an ongoing attempt at integrating the geolocation part in the workflow, and my *R* got so bad in the last 5 years that it's painful. I had to google how to install packages. 😞 

(pinging @sguth1993 )

### CODE REVIEW

**Comment by taddallas** [comment]
So `packrat` is not maintained and they are switching over to `renv`. I used that, but Idk if that really solves the reproducibility issue e.g., if they switch to another package in the future. The renv.lock file still should work, so we just keep that updated and it should work. The error with the workflow now is the on `sudo apt-get install ` of the openssl library. I think renv only versions the R packages and not the necessary libraries.

**Comment by tpoisot** [comment]
Things to do

- [x] Add the API key as a secret
- [x] Add the secret as an ENV variable
- [x] Read the API key in the script
- [x] Create the folder for the output if it doesn't exist
- [x] Maybe `.gitignore` everything that `renv` creates?

**Comment by tpoisot** [comment]
@sguth1993 do you have an API key?

**Comment by tpoisot** [comment]
The R setup seems to crash - do we need the very latest version? Would it be more stable on OS X or windows?

**Comment by tpoisot** [comment]
Additional question for maybe @taddallas - is there a way to install dependencies regardless of the platform?

**Comment by taddallas** [comment]
I think the crash is not R, but OS error. 

```
Err:1 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 gdebi-core all 0.9.5.7+nmu2
```

It is a bit annoyingly unstable. All the R and renv stuff should be platform agnostic, but the sudo command for the installation of the one library is obviously not.

**Comment by tpoisot** [comment]
Let's try with the older ubuntu?

**Comment by sguth1993** [comment]
API is **removed by @tpoisot**
Sounds like if we go over the geocode request limit (2500/day), we'll just get an error message and if it happens a lot, Google might block access

Sorry I'm causing trouble with R... I also don't have much experience with github so still figuring out how to navigate the repo

**Comment by tpoisot** [comment]
OK, here is the current solution -- we run the script once a week, and the results are pushed to master. This is not ideal in terms of having artifacts in the repo, but this will avoid too many calls to the API. Running the script once a week should be a good comprise between updating things frequently enough, and minimizing API calls.

**Comment by tpoisot** [comment]
Well, if all goes well, we should have an output in about 10 minutes...

**Pull request merged**
